version: '3'
services:
  db:
    image: mysql:5.7.21
    restart: always
    environment:
      MYSQL_USER: me
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
  adminer:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8081:80"
  apache:
    image: webdevops/php-apache-dev
    command: bash -c "
    apt-get -y update
    && apt-get install -q -y software-properties-common
    && add-apt-repository ppa:certbot/certbot 
    && apt-get -y update 
    && apt-get install -q -y python-certbot-apache 
    && apt-get clean
    && certbot -n --expand --apache --agree-tos --email 'nvienot@gmail.com' --domains 'camagru.ga' "
    restart: always
    environment:
      CAMAGRU_DBNAME: 'camagru'
      CAMAGRU_DBUSER: 'root'
      CAMAGRU_DBPASSWORD: 'password'
      CAMAGRU_DBHOST: db
      CAMAGRU_ROOT: https://35.189.123.16/
    volumes:
      - .:/app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    links:
      - db
