version: '3'
services:
  db:
    image: mysql:5.7.21
    restart: always
    environment:
      MYSQL_USER: me
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
  adminer:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8081:80"
  apache:
    image: webdevops/php-apache-dev
    restart: always
    environment:
      CAMAGRU_DBNAME: "camagru"
      CAMAGRU_DBUSER: "root"
      CAMAGRU_DBPASSWORD: "password"
      CAMAGRU_DBHOST: db
      CAMAGRU_ROOT: https://camagru.cf/

    volumes:
      - .:/app
      - ./.docker/camagru.cf/camagru.cf.conf:/opt/docker/etc/httpd/vhost.conf
      - ./.docker/letsencrypt:/etc/letsencrypt
    ports:
      - "2525:2525"
      - "465:465"
      - "587:587"
      - "80:80"
      - "443:443"
    depends_on:
      - db
    links:
      - db
