version: '3'
services:
  db:
    image: mysql:5.7.21
    restart: always
    environment:
      MYSQL_USER: me
      MYSQL_PASSWORD: ${CAMAGRU_DBPASSWORD}
      MYSQL_ROOT_PASSWORD: ${CAMAGRU_DBPASSWORD}
    ports:
      - "3306:3306"
  adminer:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8081:80"
  apache:
    image: webdevops/php-apache-dev
    restart: always
    environment:
      CAMAGRU_DBNAME: ${CAMAGRU_DBNAME}
      CAMAGRU_DBUSER: ${CAMAGRU_DBUSER}
      CAMAGRU_DBPASSWORD: ${CAMAGRU_DBPASSWORD}
      CAMAGRU_DBHOST: db
    volumes:
      - .:/app
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - db
    links:
      - db